apiVersion: v1
kind: Service
metadata:
  name: llm-inference-service
  labels:
    app: llm-inference-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    name: http
  - port: 8001
    targetPort: 8001
    name: grpc
  - port: 8002
    targetPort: 8002
    name: metrics
  selector:
    app: llm-inference-server
